### ISSUE TITLE
Back Buttons not reversing Behaviour in every Case

### ISSUE THREAD

**Issue by FinnIckler** [AllieTurner/brexit_tweet_analysis#1]
For some of the screens the back button is not reversing the step, For example when new data is loaded

**Comment by sousalui** [comment]
Is it possible to write the code back for when you press the back button it goes back to the previous page (as if it was a new page)?

**Comment by FinnIckler** [comment]
The back buttons where fixed for all clicks expect for new loads in 5845999e94d8216735e5e289a638bc6c51a80d3a . The problem with new loads is that you can't load more nodes into the circles than before.
