### ISSUE TITLE
Website should have scrolling!

### ISSUE THREAD

**Issue by AllieTurner** [AllieTurner/brexit_tweet_analysis#2]

**Comment by FinnIckler** [comment]
While this is a good idea, I don't know how this change would impact performance, as currently the data is loaded into the system on the fly. To fix this we could just load all the data at the start and hotswap them. I will look into this

**Comment by AllieTurner** [comment]
A good example can be found here: https://www.svt.se/special/the-swedes-in-paradise-papers/

**Comment by FinnIckler** [comment]
Putting this as won't fix after examining the load times of changing the data, even when loaded beforehand. For this to work the whole structure of the simulation has to be changed, basically we would need to have all nodes present at any time, but fading out the irrelevant ones. Maybe someday ;).
