### ISSUE TITLE
Unable to adapt map view pages to different screen resolutions. 

### ISSUE THREAD

**Issue by sousalui** [AllieTurner/brexit_tweet_analysis#3]
As the map used is in SVG format, the website only displays the dots correctly on the map on a 1280x800 scale. Any other display resolution will prevent the reader from being the location accurately.

**Comment by FinnIckler** [comment]
I think this can be fixed by making the map the background of the visualization instead of the body . I will get to it asap

**Comment by sousalui** [comment]
Thanks Finn!

**Comment by AllieTurner** [comment]
Can we make the visualization scalable for all screen sizes in the future? What kind of graphics do you need for that?

**Comment by FinnIckler** [comment]
We could set the height and width to 100% of the screen and then work from there. We would have to make multiple versions of the map and exchange it depending on the screen resolution though.
